host = "psu-clementine.network"
patch_port = 11030
login_port = 12030
# Disable the minimap. The minimap appears broken on resolutions other than
# 1280x720, so this may be preferable.
disable_minimap = false

# In order for the following settings to work, you must set the mode in
# option.exe to 1280x720 windowed.
width = 1280
height = 720
# Maximizes and sets the window to borderless mode.
borderless = false


####   Here be dragons    ####
#### i.e. DEVELOPERS ONLY ####

# Override and disable filename hashing.
# You will have to specify a hashed_names_path.
# e.g. Copy your DATA directory to DATA_Hashed
# and uncomment the setting below. This will allow
# the plugin to copy hashed files into their real
# filenames dynamically, progressively building up
# your unhashed DATA directory.
disable_md5_filename_hashing = false
#hashed_names_path = "DATA_Hashed"