host = "psu-clementine.ddns.net"
patch_port = 11030
login_port = 12030

# In order for the following settings to work, you must set the mode in
# option.exe to 1280x720 windowed.
width = 1280
height = 720
borderless = false
